branch-defaults:
  default:
    environment: Myudagramapi-env
environment-defaults:
  Myudagramapi-env:
    branch: null
    repository: null
global:
  aws_access_key_id: eb --version
  aws_secret_access_key: xLSWaAaWiEGpeKhCl+nE3pS/Q4fnKPjcXZKZPLEh
  application_name: myudagram-api
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
